src/views/Team.vue

fixed color bug team page

---

src/components/layout/Navbar.vue

header css bug fixed 

---

src/i18n/messages.json

**What kind of change does this PR introduce?** (check at least one)
If yes, please describe the impact and migration path for existing applications: -
If adding a **new feature**, the PR's description includes:
**Other information:**

chore: Edit headline with new text content (fix: #20)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

If this is your first pull request that you open, please read this [open source contribution guide](https://opensource.guide/how-to-contribute/#opening-a-pull-request).
**Summary**
This pull request aims to add two issue templates that will help the contributor to accelerate the process of creating an issue. The two possible selections are:
- Bug reports: this one will allow the contributor to point any type of bug that it's presented in the repository.
- Future request: this one will allow the contributor to provide an explanation on any feature requests that they think it's needed in the project.
Docs: Update issue templates …

docs: Update issues template (fix:#12)

---

.github/pull_request_template.md

If this is your first pull request that you open, please read this [open source contribution guide](https://opensource.guide/how-to-contribute/#opening-a-pull-request).
**Summary**
This pull request aims to create a PR template that will help to accelerate the process of creating and closing one as it adheres to a guideline that every user that contributes to the project can follow.
Documentation update.
If yes, please describe the impact and migration path for existing applications: -
**Screenshots and videos**
This pull request is utilizing the same template to provide visualization on how it will look like.
**The PR …

docs: Create pull request template (fix: #11)

---

src/i18n/messages.json
src/views/Event.vue

**Summary**
- Add our OsDay2023 in the events list

Add OsDay2023 as new event

---

src/i18n/messages.json

feat(i18n): remove old team members

---

src/i18n/messages.json

Amended the submit an idea link which is currently linking to a broken github page

Update messages.json text

---

package-lock.json
package.json

Updated the next dependencies used in this project: 
- @antfu/eslint-config
- @types/node
- @unocss/preset-attributify
- @unocss/preset-icons
- @unocss/preset-uno
- @unocss/preset-web-fonts
- @unocss/reset
- cypress
- unocss
- vitest

chore: update project dependencies

---

package-lock.json
package.json

Update Vue to [3.3.4](https://blog.vuejs.org/posts/vue-3-3).
If adding a **new feature**, the PR's description includes:

chore(deps): update vue to 3.3.4

---

index.html
package-lock.json
package.json
src/App.vue
src/i18n/messages.ts
src/main.ts
src/views/CodeConduct.vue
src/views/EventList.vue
src/views/EventView.vue
src/views/PageHome.vue
src/views/TeamMember.vue
src/views/TeamPage.vue

- Adds [Unhead](https://unhead.unjs.io/) to the project
- Deletes old `<title>` and `<meta>` tags in the `index.html` file
- Adds specific title to the pages depending on wherever the user finds itself
- Closes https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/98
- Pushes forward https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/93 by improving views information.
- For more information on the supported file image/file types and the file size limits, please refer
to the following [link](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files).
**The PR …

feat: utilize @unhead/vue, modify views <head> element

---

index.html
src/App.vue
src/components/TheContributing.vue
src/components/buttons/CtaComponent.vue
src/components/buttons/CtaIcon.vue
src/components/buttons/LogoAnimated.vue
src/components/layout/TheNavbar.vue
src/functions/useNewsletter.ts
src/i18n/messages.ts
src/views/CodeConduct.vue
src/views/PageHome.vue
src/views/TeamMember.vue
src/views/TeamPage.vue

This is a Wip PR and refers to issue #70 - Improve accessibility
This PR contains the changes necessary to obtain the minimal accessibility requirements, such as:
- fix the descending order of the headings;
- addition of aria-label to all elements that concern the readability and interactivity of the page;
- addition of tab navigation to all text on pages, so it can be read by any screen reader;
The purpose of these changes is to make the entire website accessible via screenreaders and/or keyboard navigation.
**Other information:**
- As a suggestion, until there is a multilanguage option and a language switcher, it might be better to change the lang tag in index.html to <html lang="it"> so …

Feature: Improve accessibility

---

src/pages/CodeConduct.vue

**Summary**
Same PR as #107 when i tried to read the code of conduct to check the checkbox
**Other information:**
- Add any other context about the pull request here.

fix(CodeConduct): use fallback to fallbackLocale to access translation object

---

src/App.vue
src/components/buttons/CtaComponent.vue
src/components/layout/MobileMenu.vue
src/components/layout/TheBanner.vue
src/functions/useBannerCookie.ts
src/i18n/messages.ts
src/pages/PageHome.vue
src/styles/_variables.scss
unocss.config.ts

**Summary**
- Remove Spotify Button, add OSDay button
- Add dismissible banner which appears again on 7 days
- Closes #97
If adding a **new feature**, the PR's description includes:

feature: remove spotify button, implement OSDay button and banner

---

README.md

docs(README): update node and npm values

---

src/components/buttons/CtaComponent.vue
src/components/buttons/CtaIcon.vue
src/components/layout/TheNavbar.vue
src/styles/_variables.scss
vite.config.ts

**Summary**
- Utilize Iconify component
- Utilize Carbon Icons by default
- Utilize UnoCSS preset attributify
- Fix bug on Cta* that was duplicat ing the class attribute
If adding a **new feature**, the PR's description includes:

refactor(CtaIcon): reduce boilerplate, utilize Icon component

---

src/components/TheContributing.vue

feat: remove codemotion, closes #126

---

src/components/layout/TheBanner.vue

Forcefully disables osday banner

feat: Disable OSDay banner

---

LICENSE

license: add LICENSE as GNU Affero 3

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md
README.md
_redirects

Passing to .org domain and add redirects

feat(new domain): transfer to .org

---

.gitignore
src/App.vue
src/components/layout/TheBanner.vue

Make banner generic to allow displaying of diverse content in the app.
Enables https://github.com/Schroedinger-Hat/schroedinger-hat/issues/214
Enables https://github.com/Schroedinger-Hat/schroedinger-hat/issues/186

Make Banner component generic

---

src/App.vue
src/components/layout/TheBanner.vue
src/i18n/messages.ts

https://github.com/Schroedinger-Hat/schroedinger-hat/issues/214
Implement shop banner in the website. Should be merged whenever we release the LinkedIn post

Implement Banner shop

---

README.md
cypress/e2e/spec.cy.ts
src/components/TheContributing.vue

https://github.com/Schroedinger-Hat/schroedinger-hat/issues/227
Update linkedin links

chore: update linkedin links

---

src/i18n/events/event/osday-24.json
src/i18n/events/event/osday-25.json
src/i18n/events/index.ts
src/pages/PageHome.vue

https://github.com/Schroedinger-Hat/schroedinger-hat/issues/273
Resolves https://github.com/Schroedinger-Hat/schroedinger-hat/issues/273.
To be merged after the publication of the tickets for OSDay 25.
Banner image for event still missing.

Create OSDay 25 event

---

src/app/(website)/page.tsx

Separated the sponsor from the partner as Hetzner requires a different naming.
I haven't tested it locally as I can't install the dependencies.

feat: separating business partner to sponsor/supporters

---

src/app/sitemap.ts

It fixes the sitemap generation otherwise google webmaster tool is not taking it correctly

fix(sitemap): fix url

---

src/app/(website)/association/join/components/membership-form-modal.tsx

fix(statute link)

---

lostpixel.config.ts

PR screenshots are taken onpage load but most of Next images are lazy loaded when they enter viewport and we also have custom animations inside the page.
This PR wants address the randomness of the screenshot by waiting for the page to be ready, scrolling to the bottom and adding some delay to wait all the animations to complete

Fixed lostPixel flakiness

---

.gitignore
src/components/organisms/footer.tsx

No issue
Adds a GitHub icon on the footer so the redirection to the GitHub page of the association is easier.
Adds `target="_blank"` to anchors of Linkedin, Youtube and the newly GitHub that are in the footer

feat(footer.tsx): add GitHub icon

---

README.md

Fixes some README.md typos
Resolves #161

fix: README.md typos

---

LICENSE

No linked issue
Adds License GNU Affero v3 to the project

docs(LICENSE): add GNU Affero v3

---

prisma/migrations/20250410144426_add_nationality_field/migration.sql
prisma/schema.prisma
src/app/(website)/association/join/components/membership-form-modal.tsx
src/components/ui/select.tsx
src/server/api/routers/stripe.ts

Add nationality field
Based on that the codice fiscale is optional or mandatory (e.g. for italian folks).
Changed the where clause on the email as unique identifier (reflected on db) instead of cod fiscale.

Enable international membership subscription

---

.github/pull.yml
.github/workflows/sync-fork.yml

chore: remove pull and add a custom sync for forks

---

.github/workflows/ci.yml

It'll address the CI issue on the and closes #172 
The Pixel implementation still need an approve on the integration page as it still finds out some differences in screenshots
> While actions/setup-node@v2 may continue to function for now, it relies on an outdated version of actions/cache, which is scheduled for permanent shutdown on April 15th.

fix(ci): upgrade deprecated gh node

---

.env.example
src/app/(website)/association/newsletter/page.tsx
src/app/api/email-octopus/newsletters/route.ts
src/app/api/email-octopus/route.ts
src/components/molecules/newsletter-signup/index.tsx
src/components/molecules/past-newsletters/index.tsx
src/components/organisms/header/data.tsx
src/components/ui/button.tsx
src/components/ui/skeleton.tsx
src/env.js

Add newsletter page with the past newsletter sent to our main list
Add bottom section for subscription and a signup form on the above the fold section

feat(newsletter): add newsletter page

---

src/app/feed.xml/route.ts

Add content directly in RSS so it can read directly on a RSS viewer

feat(rss): add content in rss

---

README.md

No issue involved, this PR adds the list of project maintaners.
Add the list of project maintainers in Readme

chore(README.md): add maintainers

---

next.config.js
search-implementation.md
src/app/api/algolia/route.ts
src/components/molecules/search-command.tsx
src/components/molecules/search/search-command.tsx
src/components/organisms/global-search.tsx
src/components/ui/command.tsx
src/env.js
src/lib/hooks/use-debounce.ts
src/lib/search-service.ts
src/lib/utils/urlBuilders.ts
src/sanity/lib/live.ts

chore(autofix): apply formatting

---

.github/ISSUE_TEMPLATE/feature_request.yml

chore: remove unnecesary module line

---

src/components/organisms/header/banner-code.tsx

No issue as it was a quick fix.
Banner wasn't working well responsively in mobile and tablet. With this fix it should work accordingly.

Style: Address banner code responsiveness
